//WARNING: Don't edit. Automatically regenerated file (TLUT flow)
#include "locations.h"

const lutlocation location_array[NUMBER_OF_INSTANCES][NUMBER_OF_TLUTS_PER_INSTANCE] = {
	{		{60,0,XHI_CLB_SLICEL_EVEN,XHI_CLB_LUT_B6LUT},
			{60,2,XHI_CLB_SLICEL_EVEN,XHI_CLB_LUT_B6LUT},
			{60,2,XHI_CLB_SLICEL_EVEN,XHI_CLB_LUT_A6LUT},
			{60,1,XHI_CLB_SLICEL_EVEN,XHI_CLB_LUT_D6LUT},
			{60,5,XHI_CLB_SLICEL_EVEN,XHI_CLB_LUT_C6LUT},
			{60,3,XHI_CLB_SLICEL_EVEN,XHI_CLB_LUT_D6LUT},
			{60,4,XHI_CLB_SLICEL_EVEN,XHI_CLB_LUT_D6LUT},
			{60,4,XHI_CLB_SLICEL_EVEN,XHI_CLB_LUT_A6LUT},
			{60,2,XHI_CLB_SLICEL_EVEN,XHI_CLB_LUT_D6LUT},
			{60,0,XHI_CLB_SLICEL_EVEN,XHI_CLB_LUT_C6LUT},
			{60,2,XHI_CLB_SLICEL_EVEN,XHI_CLB_LUT_C6LUT},
			{60,0,XHI_CLB_SLICEL_EVEN,XHI_CLB_LUT_D6LUT},
			{60,1,XHI_CLB_SLICEL_EVEN,XHI_CLB_LUT_B6LUT},
			{60,3,XHI_CLB_SLICEL_EVEN,XHI_CLB_LUT_A6LUT},
			{60,0,XHI_CLB_SLICEL_EVEN,XHI_CLB_LUT_A6LUT},
			{60,1,XHI_CLB_SLICEL_EVEN,XHI_CLB_LUT_A6LUT},
			{60,5,XHI_CLB_SLICEL_EVEN,XHI_CLB_LUT_B6LUT},
			{60,3,XHI_CLB_SLICEL_EVEN,XHI_CLB_LUT_B6LUT},
			{60,4,XHI_CLB_SLICEL_EVEN,XHI_CLB_LUT_B6LUT},
			{60,3,XHI_CLB_SLICEL_EVEN,XHI_CLB_LUT_C6LUT},
			{60,7,XHI_CLB_SLICEL_EVEN,XHI_CLB_LUT_C6LUT},
			{60,7,XHI_CLB_SLICEL_EVEN,XHI_CLB_LUT_B6LUT},
			{60,6,XHI_CLB_SLICEL_EVEN,XHI_CLB_LUT_A6LUT},
			{60,5,XHI_CLB_SLICEL_EVEN,XHI_CLB_LUT_D6LUT},
			{60,4,XHI_CLB_SLICEL_EVEN,XHI_CLB_LUT_C6LUT},
			{60,1,XHI_CLB_SLICEL_EVEN,XHI_CLB_LUT_C6LUT},
			{60,6,XHI_CLB_SLICEL_EVEN,XHI_CLB_LUT_C6LUT},
			{60,5,XHI_CLB_SLICEL_EVEN,XHI_CLB_LUT_A6LUT},
			{60,7,XHI_CLB_SLICEL_EVEN,XHI_CLB_LUT_D6LUT},
			{60,6,XHI_CLB_SLICEL_EVEN,XHI_CLB_LUT_D6LUT},
			{60,7,XHI_CLB_SLICEL_EVEN,XHI_CLB_LUT_A6LUT},
			{60,6,XHI_CLB_SLICEL_EVEN,XHI_CLB_LUT_B6LUT}
	} /* axi_xor_0/axi_xor_0/USER_LOGIC_I/EXORS/exorw */
};
